### ISSUE TITLE
ircd starts up on first 'start', but not on restart of subsequent starts

### ISSUE THREAD

**Issue by DanielOaks** [linostar/rizon-docker#4]
This is weird. The first time I run `start` on it, it boots up and all just fine. After running `restart` or `stop`/`start`, the ircd won't get running.

I'll investigate here, see if it's just some strange issue related to OSX.

**Comment by linostar** [comment]
I wasn't able to reproduce it on Linux. It may be that you tried to connect to the ircd before it finished booting up. You can check by attaching to the ircd container using `rizon-docker.sh shell ircd 0` and then run `ps` there or inspect the ircd logs.

**Comment by DanielOaks** [comment]
...Apparently fixed. I did some `ps`ing before and was sure it wasn't creating `ircd` but eh. If it happens again, I'll track it down and see exactly what's going on here. Thanks for trying to repro!
